// openings.js - Extended Library of Openings, Defenses, Traps & Historical Positions
const CHESS_OPENINGS = {
    // --- Classical King's Pawn Openings (1.e4 e5) ---
    "e4 e5": "📖 King's Pawn Game (Open Game)\nThe most classical chess start, fighting for immediate center dominance.",
    "e4 e5 Nf3 Nc6 Bb5": "📖 Ruy Lopez (Spanish Opening)\nOne of the oldest and most deeply analyzed openings in chess history!",
    "e4 e5 Nf3 Nc6 Bb5 a6": "📖 Ruy Lopez: Morphy Defense\nNamed after Paul Morphy; forces White's Bishop to choose a line.",
    "e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7 Re1 b5 Bb3 d6 c3 O-O h3": "📖 Ruy Lopez: Closed Main Line (Chigorin/Breyer Setup)",
    "e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O b5 Bb3 Bb7": "📖 Ruy Lopez: Archangel Variation",
    "e4 e5 Nf3 Nc6 Bb5 a6 Ba4 Nf6 O-O Be7 Re1 b5 Bb3 O-O c3 d5": "⚠️ Ruy Lopez: Marshall Attack!\nBlack sacrifices a pawn for a devastating, long-term kingside initiative!",
    "e4 e5 Nf3 Nc6 Bb5 Nf6": "📖 Ruy Lopez: Berlin Defense\nThe 'Berlin Wall' famously used by Vladimir Kramnik to defeat Garry Kasparov in 2000.",
    "e4 e5 Nf3 Nc6 Bb5 f5": "📖 Ruy Lopez: Schliemann-Jaenisch Gambit\nAn aggressive early counter-strike against the Spanish Bishop.",
    "e4 e5 Nf3 Nc6 Bc4": "📖 Italian Game (Giuoco Piano)\nA classical opening focusing on rapid development towards f7.",
    "e4 e5 Nf3 Nc6 Bc4 Bc5": "📖 Giuoco Piano (Quiet Game)\nA balanced classical position focusing on solid pawn centers.",
    "e4 e5 Nf3 Nc6 Bc4 Bc5 b4": "📖 Evans Gambit\nA romantic 19th-century gambit sacrificing a pawn for a devastating pawn center!",
    "e4 e5 Nf3 Nc6 Bc4 Nf6": "📖 Two Knights Defense\nLeads to sharp tactical fights like the Fried Liver Attack!",
    "e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 d5 exd5 Nxd5 Nxf7": "⚠️ Fried Liver Attack!\nWhite sacrifices a Knight on f7 to pull Black's King out into the open!",
    "e4 e5 Nf3 Nc6 Bc4 Nf6 Ng5 d5 exd5 Na5": "📖 Two Knights Defense: Polerio Counterattack\nThe main theoretical refute to White's early Ng5 attack.",
    "e4 e5 Nf3 Nc6 Bc4 Be7": "📖 Hungarian Defense\nA quiet defense avoiding the tactics of the Italian Game.",
    "e4 e5 Nf3 Nc6 d4": "📖 Scotch Game\nDirect central breakthrough popularized in modern times by Garry Kasparov.",
    "e4 e5 Nf3 Nc6 d4 exd4 Nxd4 Nf6": "📖 Scotch Game: Schmidt Variation",
    "e4 e5 Nf3 Nc6 d4 exd4 Bc4": "📖 Scotch Gambit\nWhite gambits a pawn for rapid development and attacking lines.",
    "e4 e5 Nf3 Nc6 Nc3 Nf6": "📖 Four Knights Game\nA solid, classical development system for both sides.",
    "e4 e5 Nf3 Nc6 Nc3 Nf6 Bb5 Bb4 O-O O-O d3 d6 Bg5 Bxc3 bxc3 Qe7": "📖 Four Knights Game: Double Spanish Main Line",
    "e4 e5 Nf3 Nf6": "📖 Petrov's Defense (Russian Game)\nA solid, symmetrical counter-attacking system favored by world champions.",
    "e4 e5 Nf3 d6": "📖 Philidor Defense\nA sturdy but somewhat cramped defense named after François-André Danican Philidor.",
    "e4 e5 Nf3 f5": "📖 Latvian Gambit\nA violent, highly risky counter-attack by Black on move 2.",
    "e4 e5 Nf3 d5": "📖 Elephant Gambit\nBlack immediately challenges e4; aggressive but risky.",
    "e4 e5 f4": "📖 King's Gambit\nRomantic Era aggressive opening sacrificing a pawn for total central control!",
    "e4 e5 f4 exf4": "📖 King's Gambit Accepted\nBlack accepts the sacrifice, leading to highly tactical games.",
    "e4 e5 f4 exf4 Nf3 g5": "📖 King's Gambit Accepted: Classical Main Line",
    "e4 e5 f4 d5": "📖 King's Gambit: Falkbeer Countergambit\nBlack refuses the pawn and strikes back directly in the center with d5!",
    "e4 e5 d4 exd4 c3": "📖 Danish Gambit\nWhite gambits two pawns for maximum bishop development speed.",
    "e4 e5 Nc3": "📖 Vienna Game\nWhite develops the knight behind the c-pawn, keeping the option for f4 open.",

    // --- Sicilian Defense Variations (1.e4 c5) ---
    "e4 c5": "📖 Sicilian Defense\nThe most popular and sharpest response to 1.e4 at all levels!",
    "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6": "📖 Sicilian Defense: Najdorf Variation\nThe legendary weapon of Bobby Fischer and Garry Kasparov!",
    "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 g6": "📖 Sicilian Defense: Dragon Variation\nFierce asymmetrical game featuring a fianchettoed dragon bishop on g7.",
    "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 e6": "📖 Sicilian Defense: Scheveningen Variation\nA solid classical pawn small-center setup.",
    "e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 Nf6 Nc3 e5": "📖 Sicilian Defense: Sveshnikov Variation\nAggressive setup pushing e5 to seize central initiative.",
    "e4 c5 Nf3 Nc6 d4 cxd4 Nxd4 g6": "📖 Sicilian Defense: Accelerated Dragon\nBlack fianchettoes the Bishop without spending a move on d6.",
    "e4 c5 Nf3 e6 d4 cxd4 Nxd4 a6": "📖 Sicilian Defense: Kan / Paulsen Variation",
    "e4 c5 Nf3 e6 d4 cxd4 Nxd4 Nc6": "📖 Sicilian Defense: Taimanov Variation",
    "e4 c5 c3": "📖 Sicilian Defense: Alapin Variation\nWhite prepares d4 with c3, bypassing dense main-line theory.",
    "e4 c5 d4 cxd4 c3": "📖 Sicilian Defense: Smith-Morra Gambit\nWhite sacrifices a pawn for rapid development against the Sicilian.",
    "e4 c5 Nc3": "📖 Closed Sicilian\nWhite avoids opening the center early, planning a kingside expansion.",
    "e4 c5 f4": "📖 Sicilian Defense: Grand Prix Attack\nAn aggressive White system using f4 to build a kingside attack.",
    "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 Bg5 e6 f4 Qb6": "📖 Sicilian Najdorf: Poisoned Pawn Variation\nBlack steals the b2 pawn with the Queen in an ultra-sharp theoretical battle!",

    // --- Other Asymmetrical e4 Defenses ---
    "e4 e6": "📖 French Defense\nA rock-solid counter-attacking defense creating a strong pawn chain.",
    "e4 e6 d4 d5 Nc3 Nf6 Bg5 Bb4": "📖 French Defense: Winawer Variation\nSharp positional fight with doubled pawns and central pressure.",
    "e4 e6 d4 d5 Nc3 dxe4 Nxe4 Nd7": "📖 French Defense: Rubinstein Variation",
    "e4 e6 d4 d5 e5": "📖 French Defense: Advance Variation\nWhite closes the center, gaining kingside space.",
    "e4 e6 d4 d5 exd5 exd5": "📖 French Defense: Exchange Variation\nLeads to a highly symmetrical and drawish pawn structure.",
    "e4 c6": "📖 Caro-Kann Defense\nExtremely durable defense favored for its solid pawn structure and healthy endgames.",
    "e4 c6 d4 d5 Nc3 dxe4 Nxe4 Bf5": "📖 Caro-Kann: Classical Variation",
    "e4 c6 d4 d5 Nc3 dxe4 Nxe4 Nd7": "📖 Caro-Kann: Steinitz / Modern Variation",
    "e4 c6 d4 d5 e5 Bf5": "📖 Caro-Kann: Advance Variation",
    "e4 c6 d4 d5 exd5 cxd5 c4": "📖 Caro-Kann: Panov-Botvinnik Attack\nWhite opens lines and accepts an Isolated Queen's Pawn (IQP) for piece activity.",
    "e4 d6": "📖 Pirc Defense\nHypermodern approach: allowing White center space to strike back later.",
    "e4 g6": "📖 Modern Defense (King's Fianchetto)",
    "e4 Nf6": "📖 Alekhine's Defense\nNamed after World Champion Alexander Alekhine; provokes White's center pawns forward.",
    "e4 Nc6": "📖 Nimzowitsch Defense",
    "e4 d5": "📖 Scandinavian Defense\nBlack immediately strikes the center; leads to early queen movement.",
    "e4 d5 exd5 Qxd5 Nc3 Qa5": "📖 Scandinavian Defense: Main Line (Qa5)",
    "e4 d5 exd5 Nf6": "📖 Scandinavian Defense: Modern Variation (Nf6)",

    // --- Queen's Pawn Openings & Defenses (1.d4) ---
    "d4 d5": "📖 Queen's Pawn Game (Closed Game)",
    "d4 d5 c4": "📖 Queen's Gambit\nStrategic gambit offering a wing pawn for total center dominance.",
    "d4 d5 c4 e6": "📖 Queen's Gambit Declined (QGD)\nA fortress-like defense favored in World Championship matches.",
    "d4 d5 c4 e6 Nc3 Nf6 Bg5 Be7 e3 O-O Nf3 h6 Bh4 b6": "📖 QGD: Tartakower System\nA battle-tested defense creating a hyper-solid pawn structure.",
    "d4 d5 c4 e6 Nc3 Nf6 cxd5 exd5": "📖 QGD: Exchange Variation (Carlsbad Pawn Structure)\nClassic pawn structure leading to White's minority attack on the queenside.",
    "d4 d5 c4 dxc4": "📖 Queen's Gambit Accepted (QGA)",
    "d4 d5 c4 c6": "📖 Slav Defense\nA premier defense against 1.d4 maintaining strong central pawn support.",
    "d4 d5 c4 c6 Nf3 Nf6 Nc3 dxc4 a4": "📖 Slav Defense: Alapin Variation",
    "d4 d5 c4 e6 Nc3 c6": "📖 Semi-Slav Defense\nCombines the best of the QGD and Slav, leading to ultra-complex games.",
    "d4 d5 c4 e6 Nc3 c6 Nf3 Nf6 e3 Nbd7 Bd3 dxc4 Bxc4 b5": "📖 Semi-Slav: Meran Variation\nOne of the most razor-sharp, deeply analyzed systems in chess theory!",
    "d4 d5 Nf3 Nf6 c4 e6 Nc3 c5": "📖 Tarrasch Defense\nBlack accepts an Isolated Queen's Pawn (IQP) for free piece play.",
    "d4 d5 e4": "⚠️ Blackmar-Diemer Gambit\nWhite sacrifices a pawn on move 2 for rapid development and open lines!",
    "d4 d5 Bf4": "📖 London System\nA solid, flexible setup popular for its universal schematic play.",
    "d4 d5 Nf3 Nf6 BF4": "📖 London System: Main Line",
    "d4 d5 c4 e5": "📖 Albin Countergambit\nBlack gambits e5 to create a dangerous wedge pawn on d3!",

    // --- Indian Defenses (1.d4 Nf6) ---
    "d4 Nf6": "📖 Indian Defenses\nHypermodern responses allowing White an early center to counter-attack it.",
    "d4 Nf6 c4 e6 Nc3 Bb4": "📖 Nimzo-Indian Defense\nHypermodern masterwork pinning White's knight to control e4.",
    "d4 Nf6 c4 e6 Nc3 Bb4 Qc2": "📖 Nimzo-Indian: Classical Variation (Classical Qc2)",
    "d4 Nf6 c4 e6 Nc3 Bb4 e3": "📖 Nimzo-Indian: Rubinstein System",
    "d4 Nf6 c4 e6 Nf3 b6": "📖 Queen's Indian Defense\nA solid hypermodern defense controlling e4 with b6 and Bb7.",
    "d4 Nf6 c4 g6 Nc3 d5": "📖 Grünfeld Defense\nA dynamic counter-attacking defense favored by Garry Kasparov.",
    "d4 Nf6 c4 g6 Nc3 Bg7": "📖 King's Indian Defense (KID)\nLeads to violent opposite-side pawn storms and kingside attacks!",
    "d4 Nf6 c4 g6 Nc3 Bg7 e4 d6 Nf3 O-O Be2 e5": "📖 King's Indian Defense: Classical Mar del Plata Variation",
    "d4 Nf6 c4 g6 Nc3 Bg7 e4 d6 f3": "📖 King's Indian Defense: Sämisch Variation\nWhite builds an iron pawn wall on f3 and prepares a kingside assault.",
    "d4 Nf6 c4 c5 d5": "📖 Benoni Defense\nCreates an asymmetrical pawn structure with dynamic counterplay.",
    "d4 Nf6 c4 c5 d5 b5": "📖 Benko Gambit (Volga Gambit)\nBlack sacrifices a pawn early for permanent queenside positional pressure.",
    "d4 Nf6 c4 e5": "📖 Budapest Gambit\nBlack gambits e5 immediately to disrupt White's setup.",
    "d4 Nf6 Bg5": "📖 Trompowsky Attack\nAggressive anti-Indian setup bypassing main theory.",
    "d4 f5": "📖 Dutch Defense\nUnbalanced and aggressive flank setup fighting for e4 control.",
    "d4 f5 g3 Nf6 Bg2 g6": "📖 Dutch Defense: Leningrad Variation",
    "d4 f5 c4 Nf6 g3 e6 Bg2 Be7 Nf3 O-O O-O d5": "📖 Dutch Defense: Stonewall Variation",

    // --- Flank & Offbeat Openings ---
    "c4": "📖 English Opening\nFlank opening controlling d5 and offering rich strategic options.",
    "c4 e5": "📖 English Opening: King's English Variation (Reversed Sicilian)",
    "c4 c5": "📖 English Opening: Symmetrical Variation",
    "Nf3": "📖 Réti Opening / Zukertort Opening\nHypermodern opening controlling the center from afar.",
    "f4": "📖 Bird's Opening\nDirect flank attack striving for early e5 control.",
    "f4 d5 e4": "⚠️ From's Gambit\nBlack gambits e5 to tear open White's exposed kingside!",
    "b3": "📖 Nimzo-Larsen Attack\nPrepares a powerful fianchettoed bishop on b2.",
    "g4": "📖 Grob's Attack (The Spike)\nExtremely rare, erratic and aggressive flank push!",
    "b4": "📖 Sokolsky Opening (Orangutan)\nEccentric flank movement famously played by Tartakower in 1924.",
    "a3": "📖 Anderssen's Opening",
    "Nc3": "📖 Dunst Opening (Sleipner Opening)",

    // --- Famous Traps, Early Mates & Historical Games ---
    "e4 e5 Qh5": "📖 Wayward Queen Attack (Danvers Opening)\nEarly Queen attack aiming for a quick Scholar's Mate!",
    "e4 e5 Bc4 Nc6 Qh5 g6 Qf3 Nf6 Ne2 Bg7": "⚠️ Scholar's Mate Attempt Defended!",
    "e4 e5 Qh5 g6 Qxe5+ Be7 Qxh8": "💥 Scholar's Mate Trap: Black blunder costs a Rook!",
    "e4 e5 Bc4 Bc5 Qh5 Nf6 Qxf7#": "💥 Scholar's Mate!\nClassic 4-move checkmate targeting the weak f7 square!",
    "f3 e5 g4 Qh4#": "💥 Fool's Mate!\nThe fastest possible checkmate in chess (2 moves)!",
    "e4 e5 Nf3 Nc6 Bc4 Nd4": "⚠️ Blackburne Shilling Gambit\nA famous trap setting up a sudden queen fork and smothered mate!",
    "e4 e5 Nf3 Nc6 Bc4 Nd4 Nxe5 Qg5 Nxf7 Qxg2 Rf1 Qxe4+ Be2 Nf3#": "💥 Blackburne Shilling Smothered Mate!",
    "e4 e5 Nf3 Nc6 Bb5 Nf6 O-O Nxe4 d4 Nd6 dxe5 Nxb5 a4 Nbd4 Nxd4 d5": "📖 Ruy Lopez: Berlin Endgame Position",
    "e4 e5 Nf3 d6 d4 Bg4 dxe5 Bxf3 Qxf3 dxe5 Bc4 Nf6 Qb3 Qe7 Nc3 c6 Bg5": "📖 Opera Game (Morphy vs Duke of Brunswick, 1858)\nPaul Morphy's most famous romantic-era masterpiece position!",
    "e4 Nf6 e5 Nd5 d4 d6 Nf3 g6 Bc4 Nb6 Bb3 Bg7 a4 a5 Ng5 e6 Qf3 Qe7 Ne4 h6": "📖 Game of the Century (Byrne vs Fischer, 1956)\n13-year-old Bobby Fischer played one of the greatest games in history from this setup!",
    "e4 c5 Nf3 d6 d4 cxd4 Nxd4 Nf6 Nc3 a6 Bg5 e6 f4 b5 e5 dxe5 fxe5 Qc7 exf6 Qe5+ Be2 Qxg5 O-O Ra7": "📖 Kasparov vs Deep Blue (1997)\nFamous Najdorf battle position between world champion and supercomputer!"
};